addons:
  ssh_known_hosts:
  - rey.webhouse.net
cache: npm
before_deploy:
- openssl aes-256-cbc -K $encrypted_dcb3fb68803f_key -iv $encrypted_dcb3fb68803f_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: bash scripts/deploy.sh master $TRAVIS_BUILD_DIR
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: bash scripts/deploy.sh dev $TRAVIS_BUILD_DIR
  skip_cleanup: true
  on:
    branch: dev
language: node_js
node_js:
- stable
notifications:
  email:
    recipients:
    - hh@webhouse.dk
    on_success: never
    on_failure: always
  slack: webhouseteam:82qu1PX5R5wkYNCW5x6fVlhu
script:
- npm run-script build
- cp ./build/index.html ./build/200.html